server:
  port: 9001

eureka:
  instance:
    hostname: localhost
  server:
    # 设为false，关闭自我保护
    enable-self-preservation: false
    #清理间隔（单位毫秒，默认是60*1000）启用主动失效，并且每次主动失效检测间隔为3s
    eviction-interval-timer-in-ms: 5000
    #10秒轮回路
    renewalThresholdUpdateIntervalMs: 10000
    eIPBindingRetryIntervalMsWhenUnbound: 20000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/